In [3]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a=np.arrange
print(a)

In [3]:
l=range(1000)
%timeit [i**2 for i in l]

171 μs ± 4.52 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
a =np.arange(1000)
%timeit a**2

3.09 μs ± 49.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
a= np.array([1,2,3,4])

In [9]:
print(a.ndim)

1


In [12]:
b=np.array([[1,2,3],[4,5,6]])

In [13]:
print(b.ndim)

2


In [4]:
c= np.array([[[1,2],[3,4,]],[[4,5],[6,7]]])

In [5]:
print(c)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [6]:
print(c.ndim)

3


In [47]:
print(a.shape)

(10,)


In [48]:
print(b.shape)

(5,)


In [46]:
print(c.shape)

(2, 2, 2)


In [16]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [19]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [20]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [24]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [25]:
print(np.diag(a))

[1 2 3 4]


In [26]:
a=np.arange(10)
print(a.dtype)

int64


In [32]:
a=np.arange(10,dtype="float64")
print(a.dtype)

float64


In [28]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


In [29]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [30]:
a=np.array([True,False])
print(a.dtype)

bool


In [31]:
a=np.array(['Pavi','Manasa'])
print(a.dtype)

<U6


In [33]:
a=np.arange(10)
print(a[5])

5


In [34]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [35]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [36]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
print(a[1:8:2])

[ 1  3 10 10]


In [37]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [11]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [12]:
print(np.shares_memory(a,b))

True


In [13]:
b[0]=10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [43]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [39]:
print(np.shares_memory(a,b))

False


In [41]:
b[0]=10
print(a)
print(b)

[ 0  1  2  3  4 10 10 10 10 10]
[[10 10 10]
 [ 4  5  6]]


In [51]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [15]:
a=np.random.randint(0,20,15)
print(a)

[13  0  7  7  2  0  6  4  6  2 19 17  8 14  1]


In [19]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [20]:
print(a**2)

[ 1  4  9 16]


In [56]:
a=np.array([1,2,3,4])
b=np.array([5,2,7,4])
print(a==b)

[False  True False  True]


In [57]:
print(a<b)

[ True False  True False]


In [58]:
print(a>b)

[False False False False]


In [59]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [60]:
print(np.array_equal(a,c))

True


In [61]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")

In [62]:
print(np.logical_or(a,b))

[ True  True  True False]


In [63]:
print(np.logical_and(a,b))

[ True False False False]


In [64]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [65]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [66]:
np.log(a)

C:\Users\Manasa P\AppData\Local\Temp\ipykernel_9932\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [68]:
print(np.exp(a))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [69]:
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [70]:
x=np.array([[1,2],[1,2]])
print(x)

[[1 2]
 [1 2]]


In [71]:
print(x.argmin())

0


In [72]:
print(x.argmax())

1


In [73]:
x=np.array([1,2,3,1])

In [74]:
print(x.mean())

1.75


In [75]:
print(np.median(x))

1.5


In [76]:
print(x.std())

0.82915619758885
